apiVersion: v1
kind: ServiceAccount
metadata:
  name: kactus
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kactus
rules:
  - apiGroups:
      - "extensions"
      - "kaloom.com"
    resources:
      - networks
    verbs:
      - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kactus
roleRef:
  kind: ClusterRole
  name: kactus
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kactus
  namespace: kube-system
