apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: networks.kaloom.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: kaloom.com
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: networks
    # singular name to be used as an alias on the CLI and for display
    singular: network
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Network
    listKind: NetworkList
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - net
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: 'Network is a CRD schema of the Kaloom Network Attachcmement Definition'
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: 'Network spec defines the desired state of a network attachment'
              type: object
              properties:
                plugin:
                  description: 'Network plugin defines CNI-plugin to use, this field is a copy of the "type:" element as encoded in the JSON-formatted CNI configuration below'
                  type: string
                config:
                  description: 'Network config is a JSON-formatted CNI configuration'
                  type: string
