apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app2
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        networks: '[ { "name": "green" }, { "name": "blue" } ]'
      labels:
        app: app2
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                  - app1
            topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: net-setup-net1
          image: kaloom/alpine:3.9
          env:
            - name: NET_IFNAME
              value: "net9f27410725ab" # green net
            - name: NET_IPV4_ADDRESS
              value: "192.168.42.20"
            - name: NET_IPV4_NETMASK
              value: "24"
            - name: NET_SEND_GRATUITOUS_ARP
              value: "3"
            - name: NET_IPV6_ADDRESS
              value: "fd10:42::2"
            - name: NET_IPV6_NETMASK
              value: "64"
          command:
            - "/opt/kaloom/bin/config-network.sh"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
        - name: net-setup-net2
          image: kaloom/alpine:3.9
          env:
            - name: NET_IFNAME
              value: "net48d6215903df" # blue net
            - name: NET_IPV4_ADDRESS
              value: "192.168.43.20"
            - name: NET_IPV4_NETMASK
              value: "24"
            - name: NET_SEND_GRATUITOUS_ARP
              value: "3"
            - name: NET_IPV6_ADDRESS
              value: "fd10:43::2"
            - name: NET_IPV6_NETMASK
              value: "64"
          command:
            - "/opt/kaloom/bin/config-network.sh"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      containers:
      - name: alpine-container
        image: kaloom/alpine:3.9
        imagePullPolicy: IfNotPresent
        args:
        - top
